<Type Name="UnhandledExceptionAction" FullName="System.Activities.UnhandledExceptionAction">
  <Metadata><Meta Name="ms.openlocfilehash" Value="49ec3f0e8e54b201065483c932c4fb2a0667b4b5" /><Meta Name="ms.sourcegitcommit" Value="74239f3977d28923e5020663db2c4e91601bea79" /><Meta Name="ms.translationtype" Value="MT" /><Meta Name="ms.contentlocale" Value="pl-PL" /><Meta Name="ms.lasthandoff" Value="07/24/2019" /><Meta Name="ms.locfileid" Value="68437478" /></Metadata><TypeSignature Language="C#" Value="public enum UnhandledExceptionAction" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi sealed UnhandledExceptionAction extends System.Enum" />
  <TypeSignature Language="DocId" Value="T:System.Activities.UnhandledExceptionAction" />
  <TypeSignature Language="VB.NET" Value="Public Enum UnhandledExceptionAction" />
  <TypeSignature Language="C++ CLI" Value="public enum class UnhandledExceptionAction" />
  <TypeSignature Language="F#" Value="type UnhandledExceptionAction = " />
  <AssemblyInfo>
    <AssemblyName>System.Activities</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Enum</BaseTypeName>
  </Base>
  <Docs>
    <summary><span data-ttu-id="71979-101">Określa akcję, która występuje, gdy wyjątek wyprowadza element główny przepływu pracy.</span><span class="sxs-lookup"><span data-stu-id="71979-101">Specifies the action that occurs when an exception escapes the root of a workflow.</span></span></summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="71979-102"><xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> Funkcja jest wywoływana, jeśli wyjątek wyprowadza element główny przepływu pracy.</span><span class="sxs-lookup"><span data-stu-id="71979-102">The <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> function is invoked if an exception escapes the root of the workflow.</span></span> <span data-ttu-id="71979-103">Zapewnia dostęp do wyjątku, a także wskaźnik <xref:System.Activities.Activity> do, który wygenerował wyjątek. <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs></span><span class="sxs-lookup"><span data-stu-id="71979-103">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> provides access to the exception as well as a pointer to the <xref:System.Activities.Activity> that generated the exception.</span></span> <span data-ttu-id="71979-104">Zakończenie jest akcją domyślną, jeśli <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> nie określono procedury obsługi.</span><span class="sxs-lookup"><span data-stu-id="71979-104">Terminate is the default action if no <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is specified.</span></span>  
  
   
  
## Examples

<span data-ttu-id="71979-105">Poniższy przykład wywołuje przepływ pracy, który zgłasza wyjątek.</span><span class="sxs-lookup"><span data-stu-id="71979-105">The following example invokes a workflow that throws an exception.</span></span> <span data-ttu-id="71979-106">Wyjątek jest nieobsługiwany przez przepływ pracy i <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> wywoływany jest program obsługi.</span><span class="sxs-lookup"><span data-stu-id="71979-106">The exception is unhandled by the workflow and the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="71979-107"><xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> Są one sprawdzane w celu podania informacji o wyjątku, a przepływ pracy zostaje zakończony.</span><span class="sxs-lookup"><span data-stu-id="71979-107">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> are inspected to provide information about the exception, and the workflow is terminated.</span></span>  
  
[!code-csharp[CFX_WorkflowApplicationExample#6](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#6)]  

<span data-ttu-id="71979-108">Poniższy przykład wywołuje przepływ pracy, który zgłasza wyjątek.</span><span class="sxs-lookup"><span data-stu-id="71979-108">The following example invokes a workflow that throws an exception.</span></span> <span data-ttu-id="71979-109">Wyjątek jest nieobsługiwany przez przepływ pracy i <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> wywoływany jest program obsługi.</span><span class="sxs-lookup"><span data-stu-id="71979-109">The exception is unhandled by the workflow and the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="71979-110"><xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> Są one sprawdzane w celu dostarczenia informacji o wyjątku, a przepływ pracy został przerwany.</span><span class="sxs-lookup"><span data-stu-id="71979-110">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> are inspected to provide information about the exception, and the workflow is aborted.</span></span>  
  
[!code-csharp[CFX_WorkflowApplicationExample#7](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#7)]  

<span data-ttu-id="71979-111">Poniższy przykład wywołuje przepływ pracy, który zgłasza wyjątek.</span><span class="sxs-lookup"><span data-stu-id="71979-111">The following example invokes a workflow that throws an exception.</span></span> <span data-ttu-id="71979-112">Wyjątek jest nieobsługiwany przez przepływ pracy i <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> wywoływany jest program obsługi.</span><span class="sxs-lookup"><span data-stu-id="71979-112">The exception is unhandled by the workflow and the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="71979-113"><xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> Są one sprawdzane w celu dostarczenia informacji o wyjątku, a przepływ pracy zostanie anulowany.</span><span class="sxs-lookup"><span data-stu-id="71979-113">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> are inspected to provide information about the exception, and the workflow is cancelled.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#8](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#8)]  

 ]]></format>
    </remarks>
  </Docs>
  <Members>
    <Member MemberName="Abort">
      <MemberSignature Language="C#" Value="Abort" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Activities.UnhandledExceptionAction Abort = int32(0)" />
      <MemberSignature Language="DocId" Value="F:System.Activities.UnhandledExceptionAction.Abort" />
      <MemberSignature Language="VB.NET" Value="Abort" />
      <MemberSignature Language="C++ CLI" Value="Abort" />
      <MemberSignature Language="F#" Value="Abort = 0" Usage="System.Activities.UnhandledExceptionAction.Abort" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Activities</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Activities.UnhandledExceptionAction</ReturnType>
      </ReturnValue>
      <MemberValue>0</MemberValue>
      <Docs>
        <summary><span data-ttu-id="71979-114">Określa, że <see cref="T:System.Activities.WorkflowApplication" /> powinien przerwać przepływ pracy.</span><span class="sxs-lookup"><span data-stu-id="71979-114">Specifies that the <see cref="T:System.Activities.WorkflowApplication" /> should abort the workflow.</span></span> <span data-ttu-id="71979-115">Powoduje to wywołanie delegata zwróconego przez <see cref="P:System.Activities.WorkflowApplication.Aborted" /> bJeśli proces przerwania jest zakończony.</span><span class="sxs-lookup"><span data-stu-id="71979-115">This results in the calling the delegate returned by the <see cref="P:System.Activities.WorkflowApplication.Aborted" /> bwhen the abort process is complete.</span></span> <span data-ttu-id="71979-116">Nieobsługiwany wyjątek jest używany jako powód przerwania.</span><span class="sxs-lookup"><span data-stu-id="71979-116">The unhandled exception is used as the abort reason.</span></span></summary>
      </Docs>
    </Member>
    <Member MemberName="Cancel">
      <MemberSignature Language="C#" Value="Cancel" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Activities.UnhandledExceptionAction Cancel = int32(1)" />
      <MemberSignature Language="DocId" Value="F:System.Activities.UnhandledExceptionAction.Cancel" />
      <MemberSignature Language="VB.NET" Value="Cancel" />
      <MemberSignature Language="C++ CLI" Value="Cancel" />
      <MemberSignature Language="F#" Value="Cancel = 1" Usage="System.Activities.UnhandledExceptionAction.Cancel" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Activities</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Activities.UnhandledExceptionAction</ReturnType>
      </ReturnValue>
      <MemberValue>1</MemberValue>
      <Docs>
        <summary><span data-ttu-id="71979-117">Określa, że <see cref="T:System.Activities.WorkflowApplication" /> należy zaplanować anulowanie działania głównego i wznowić wykonywanie.</span><span class="sxs-lookup"><span data-stu-id="71979-117">Specifies that the <see cref="T:System.Activities.WorkflowApplication" /> should schedule the cancellation of the root activity and resume execution.</span></span> <span data-ttu-id="71979-118">Powoduje to cakk TI obiektu delegowanego zwróconego przez <see cref="P:System.Activities.WorkflowApplication.Completed" /> właściwość po zakończeniu procesu anulowania.</span><span class="sxs-lookup"><span data-stu-id="71979-118">This results in a cakk ti the delegate returned by the <see cref="P:System.Activities.WorkflowApplication.Completed" /> property when the cancellation process is complete.</span></span></summary>
      </Docs>
    </Member>
    <Member MemberName="Terminate">
      <MemberSignature Language="C#" Value="Terminate" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Activities.UnhandledExceptionAction Terminate = int32(2)" />
      <MemberSignature Language="DocId" Value="F:System.Activities.UnhandledExceptionAction.Terminate" />
      <MemberSignature Language="VB.NET" Value="Terminate" />
      <MemberSignature Language="C++ CLI" Value="Terminate" />
      <MemberSignature Language="F#" Value="Terminate = 2" Usage="System.Activities.UnhandledExceptionAction.Terminate" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Activities</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Activities.UnhandledExceptionAction</ReturnType>
      </ReturnValue>
      <MemberValue>2</MemberValue>
      <Docs>
        <summary><span data-ttu-id="71979-119">Określa, że <see cref="T:System.Activities.WorkflowApplication" /> należy zaplanować zakończenie działania głównego i wznowić wykonywanie.</span><span class="sxs-lookup"><span data-stu-id="71979-119">Specifies that the <see cref="T:System.Activities.WorkflowApplication" /> should schedule termination of the root activity and resume execution.</span></span> <span data-ttu-id="71979-120">Powoduje to wywołanie delegata przypisanego do <see cref="P:System.Activities.WorkflowApplication.Completed" />właściwości po zakończeniu procesu kończenia.</span><span class="sxs-lookup"><span data-stu-id="71979-120">This results in a call to the delegate assigned to the <see cref="P:System.Activities.WorkflowApplication.Completed" />property when the termination process is complete.</span></span> <span data-ttu-id="71979-121">Nieobsługiwany wyjątek jest używany jako powód zakończenia.</span><span class="sxs-lookup"><span data-stu-id="71979-121">The unhandled exception is used as the termination reason.</span></span> <span data-ttu-id="71979-122"><see langword="Terminate" />jest akcją domyślną, jeśli <see cref="P:System.Activities.WorkflowApplication.OnUnhandledException" /> nie określono programu obsługi.</span><span class="sxs-lookup"><span data-stu-id="71979-122"><see langword="Terminate" /> is the default action if no <see cref="P:System.Activities.WorkflowApplication.OnUnhandledException" /> handler is specified.</span></span></summary>
      </Docs>
    </Member>
  </Members>
</Type>