<Type Name="FirstChanceExceptionEventArgs" FullName="System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs">
  <Metadata><Meta Name="ms.openlocfilehash" Value="29a24a3dad4fe1dce54dd6d4847aa5d5115398cd" /><Meta Name="ms.sourcegitcommit" Value="a3e01ec36374fac54a55add0dcc1e754e394abeb" /><Meta Name="ms.translationtype" Value="MT" /><Meta Name="ms.contentlocale" Value="pl-PL" /><Meta Name="ms.lasthandoff" Value="03/30/2019" /><Meta Name="ms.locfileid" Value="58730831" /></Metadata><TypeSignature Language="C#" Value="public class FirstChanceExceptionEventArgs : EventArgs" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi beforefieldinit FirstChanceExceptionEventArgs extends System.EventArgs" />
  <TypeSignature Language="DocId" Value="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" />
  <TypeSignature Language="VB.NET" Value="Public Class FirstChanceExceptionEventArgs&#xA;Inherits EventArgs" />
  <TypeSignature Language="C++ CLI" Value="public ref class FirstChanceExceptionEventArgs : EventArgs" />
  <TypeSignature Language="F#" Value="type FirstChanceExceptionEventArgs = class&#xA;    inherit EventArgs" />
  <AssemblyInfo>
    <AssemblyName>mscorlib</AssemblyName>
    <AssemblyVersion>2.0.5.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>netstandard</AssemblyName>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <AssemblyVersion>2.1.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>System.Runtime</AssemblyName>
    <AssemblyVersion>4.2.0.0</AssemblyVersion>
    <AssemblyVersion>4.2.1.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.EventArgs</BaseTypeName>
  </Base>
  <Interfaces />
  <Docs>
    <summary><span data-ttu-id="7ffb5-101">Udostępnia dane dla zdarzenia powiadomień, które jest wywoływane, gdy najpierw wystąpi wyjątek zarządzanych, przed rozpoczęciem środowiska uruchomieniowego języka wspólnego, wyszukując procedury obsługi zdarzeń.</span><span class="sxs-lookup"><span data-stu-id="7ffb5-101">Provides data for the notification event that is raised when a managed exception first occurs, before the common language runtime begins searching for event handlers.</span></span></summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="7ffb5-102">Ta klasa udostępnia program obsługi wyjątków dla <xref:System.AppDomain.FirstChanceException?displayProperty=nameWithType> zdarzeń z dostępem do wyjątku.</span><span class="sxs-lookup"><span data-stu-id="7ffb5-102">This class provides the exception handler for the <xref:System.AppDomain.FirstChanceException?displayProperty=nameWithType> event with access to the exception.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="7ffb5-103">Poniższy przykład tworzy serię domen aplikacji o nazwie `Child_0` za pośrednictwem `Child_3`, za pomocą `Worker` obiektu w każdej domenie aplikacji.</span><span class="sxs-lookup"><span data-stu-id="7ffb5-103">The following example creates a series of application domains named `Child_0` through `Child_3`, with a `Worker` object in each application domain.</span></span> <span data-ttu-id="7ffb5-104">Każdy `Worker` obiekt odwołuje się do `Worker` obiektu w następnej domeny aplikacji, z wyjątkiem `Worker` w to ostatnia domena aplikacji.</span><span class="sxs-lookup"><span data-stu-id="7ffb5-104">Each `Worker` object has a reference to the `Worker` object in the next application domain, except for the `Worker` in the last application domain.</span></span> <span data-ttu-id="7ffb5-105"><xref:System.AppDomain.FirstChanceException> Zdarzenie jest obsługiwane we wszystkich domenach aplikacji, z wyjątkiem `Child_1`.</span><span class="sxs-lookup"><span data-stu-id="7ffb5-105">The <xref:System.AppDomain.FirstChanceException> event is handled in all application domains except `Child_1`.</span></span>  
  
 <span data-ttu-id="7ffb5-106">Podczas tworzenia domen aplikacji domyślnej domeny aplikacji wywołuje `TestException` metodę pierwszą domenę podrzędną w aplikacji.</span><span class="sxs-lookup"><span data-stu-id="7ffb5-106">When the application domains have been created, the default application domain calls the `TestException` method for the first child application domain.</span></span> <span data-ttu-id="7ffb5-107">Każdy `Worker` obiektu wywołania `TestException` metodę dalej, aż do ostatniego `Worker` zgłasza wyjątek, który jest obsługiwany lub nieobsługiwany.</span><span class="sxs-lookup"><span data-stu-id="7ffb5-107">Each `Worker` object calls the `TestException` method for the next, until the last `Worker` throws an exception that is either handled or unhandled.</span></span> <span data-ttu-id="7ffb5-108">W efekcie bieżącego wątku przechodzi przez wszystkie domeny aplikacji i `TestException` jest dodawany do stosu w każdej domenie aplikacji.</span><span class="sxs-lookup"><span data-stu-id="7ffb5-108">Thus, the current thread passes through all the application domains, and `TestException` is added to the stack in each application domain.</span></span>  
  
 <span data-ttu-id="7ffb5-109">Podczas ostatniego `Worker` obiektu obsługuje dany wyjątek <xref:System.AppDomain.FirstChanceException> zdarzenie jest wywoływane tylko w przypadku będzie to ostatnia domena aplikacji.</span><span class="sxs-lookup"><span data-stu-id="7ffb5-109">When the last `Worker` object handles the exception, the <xref:System.AppDomain.FirstChanceException> event is raised only in the last application domain.</span></span> <span data-ttu-id="7ffb5-110">Domeny aplikacji nigdy nie uzyskać szansę, aby obsłużyć wyjątek, aby zdarzenie nie zostanie wywołane.</span><span class="sxs-lookup"><span data-stu-id="7ffb5-110">The other application domains never get a chance to handle the exception, so the event is not raised.</span></span>  
  
 <span data-ttu-id="7ffb5-111">Podczas ostatniego `Worker` obiekt nie obsługuje wyjątek, <xref:System.AppDomain.FirstChanceException> zdarzenie jest zgłaszane w każdej domenie aplikacji, która ma program obsługi zdarzeń.</span><span class="sxs-lookup"><span data-stu-id="7ffb5-111">When the last `Worker` object does not handle the exception, the <xref:System.AppDomain.FirstChanceException> event is raised in each application domain that has an event handler.</span></span> <span data-ttu-id="7ffb5-112">Po zakończeniu każdej obsługi zdarzenia stosu w dalszym ciągu Odwiń do momentu wyjątek zostaje przechwycony przez domyślnej domeny aplikacji.</span><span class="sxs-lookup"><span data-stu-id="7ffb5-112">After each event handler has finished, the stack continues to unwind until the exception is caught by the default application domain.</span></span>  
  
> [!NOTE]
>  <span data-ttu-id="7ffb5-113">Aby zobaczyć, jak wyświetlanie stosu wraz ze wzrostem, ponieważ zdarzenie jest wywoływane bliżej i bliżej domyślnej domeny aplikacji, należy zmienić `e.Exception.Message` do `e.Exception` w `FirstChanceHandler` procedury obsługi zdarzeń.</span><span class="sxs-lookup"><span data-stu-id="7ffb5-113">To see how the stack display grows as the event is raised closer and closer to the default application domain, change `e.Exception.Message` to `e.Exception` in the `FirstChanceHandler` event handlers.</span></span> <span data-ttu-id="7ffb5-114">Należy zauważyć, że w przypadku `TestException` poza granice domeny aplikacji, nazywa się pojawia się dwukrotnie: raz dla serwera proxy i jeden raz dla wycinka.</span><span class="sxs-lookup"><span data-stu-id="7ffb5-114">Notice that when `TestException` is called across application domain boundaries, it appears twice: once for the proxy and once for the stub.</span></span>  
  
 [!code-csharp[System.AppDomain.FirstChanceException#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.appdomain.firstchanceexception/cs/example.cs#1)]
 [!code-vb[System.AppDomain.FirstChanceException#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.appdomain.firstchanceexception/vb/example.vb#1)]  
  
 ]]></format>
    </remarks>
    <altmember cref="E:System.AppDomain.FirstChanceException" />
  </Docs>
  <Members>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public FirstChanceExceptionEventArgs (Exception exception);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(class System.Exception exception) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.#ctor(System.Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; FirstChanceExceptionEventArgs(Exception ^ exception);" />
      <MemberSignature Language="F#" Value="new System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs : Exception -&gt; System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" Usage="new System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs exception" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="exception" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="exception"><span data-ttu-id="7ffb5-115">Wyjątek, który właśnie został zgłoszony przez kod zarządzany, i które będą analizowane przez <see cref="E:System.AppDomain.UnhandledException" /> zdarzeń.</span><span class="sxs-lookup"><span data-stu-id="7ffb5-115">The exception that was just thrown by managed code, and that will be examined by the <see cref="E:System.AppDomain.UnhandledException" /> event.</span></span></param>
        <summary><span data-ttu-id="7ffb5-116">Inicjuje nowe wystąpienie klasy <see cref="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" /> klasy przy użyciu określonego wyjątku.</span><span class="sxs-lookup"><span data-stu-id="7ffb5-116">Initializes a new instance of the <see cref="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" /> class with a specified exception.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="7ffb5-117">Ten konstruktor jest wywoływany przez środowisko uruchomieniowe języka wspólnego, nie przez kod aplikacji.</span><span class="sxs-lookup"><span data-stu-id="7ffb5-117">This constructor is called by the common language runtime, not by application code.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="Exception">
      <MemberSignature Language="C#" Value="public Exception Exception { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance class System.Exception Exception" />
      <MemberSignature Language="DocId" Value="P:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception" />
      <MemberSignature Language="VB.NET" Value="Public ReadOnly Property Exception As Exception" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; property Exception ^ Exception { Exception ^ get(); };" />
      <MemberSignature Language="F#" Value="member this.Exception : Exception" Usage="System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
        <AssemblyVersion>2.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0;netframework-4.8">
          <AttributeName>get: System.Runtime.ConstrainedExecution.ReliabilityContract(System.Runtime.ConstrainedExecution.Consistency.WillNotCorruptState, System.Runtime.ConstrainedExecution.Cer.Success)</AttributeName>
        </Attribute>
      </Attributes>
      <ReturnValue>
        <ReturnType>System.Exception</ReturnType>
      </ReturnValue>
      <Docs>
        <summary><span data-ttu-id="7ffb5-118">Obiekt zarządzanym wyjątku, który odnosi się do wyjątku w kodzie zarządzanym.</span><span class="sxs-lookup"><span data-stu-id="7ffb5-118">The managed exception object that corresponds to the exception thrown in managed code.</span></span></summary>
        <value><span data-ttu-id="7ffb5-119">Nowo zgłoszony wyjątek.</span><span class="sxs-lookup"><span data-stu-id="7ffb5-119">The newly thrown exception.</span></span></value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="7ffb5-120">Metoda, która obsługuje <xref:System.AppDomain.UnhandledException?displayProperty=nameWithType> zdarzenia można zbadać wyjątek i wykonać odpowiednie rejestrowania lub innych usług powiadomień.</span><span class="sxs-lookup"><span data-stu-id="7ffb5-120">The method that handles the <xref:System.AppDomain.UnhandledException?displayProperty=nameWithType> event can examine the exception and perform appropriate logging or other notification services.</span></span>  
  
 <span data-ttu-id="7ffb5-121">Przykładowy kod, zobacz <xref:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs>.</span><span class="sxs-lookup"><span data-stu-id="7ffb5-121">For example code, see <xref:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs>.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>