<Type Name="FirstChanceExceptionEventArgs" FullName="System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs">
  <Metadata>
    <Meta Name="ms.openlocfilehash" Value="2030e55041a262d9e02246639317d0ba84021bfc" />
    <Meta Name="ms.sourcegitcommit" Value="6a0b904069161bbaec4ffd02aa7d9cf38c61e72e" />
    <Meta Name="ms.translationtype" Value="MT" />
    <Meta Name="ms.contentlocale" Value="pl-PL" />
    <Meta Name="ms.lasthandoff" Value="06/24/2018" />
    <Meta Name="ms.locfileid" Value="36635494" />
  </Metadata>
  <TypeSignature Language="C#" Value="public class FirstChanceExceptionEventArgs : EventArgs" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi beforefieldinit FirstChanceExceptionEventArgs extends System.EventArgs" />
  <TypeSignature Language="DocId" Value="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" />
  <TypeSignature Language="VB.NET" Value="Public Class FirstChanceExceptionEventArgs&#xA;Inherits EventArgs" />
  <TypeSignature Language="C++ CLI" Value="public ref class FirstChanceExceptionEventArgs : EventArgs" />
  <TypeSignature Language="F#" Value="type FirstChanceExceptionEventArgs = class&#xA;    inherit EventArgs" />
  <AssemblyInfo>
    <AssemblyName>mscorlib</AssemblyName>
    <AssemblyVersion>2.0.5.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>netstandard</AssemblyName>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>System.Runtime</AssemblyName>
    <AssemblyVersion>4.2.0.0</AssemblyVersion>
    <AssemblyVersion>4.2.1.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.EventArgs</BaseTypeName>
  </Base>
  <Interfaces />
  <Docs>
    <summary>
      <span data-ttu-id="99519-101">Udostępnia dane dla zdarzenia powiadomień, które jest wywoływane, gdy najpierw wystąpi wyjątek zarządzanych, przed rozpoczęciem środowisko uruchomieniowe języka wspólnego wyszukiwanie programów obsługi zdarzeń.</span>
      <span class="sxs-lookup">
        <span data-stu-id="99519-101">Provides data for the notification event that is raised when a managed exception first occurs, before the common language runtime begins searching for event handlers.</span>
      </span>
    </summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="99519-102">Ta klasa udostępnia program obsługi wyjątku dla <xref:System.AppDomain.FirstChanceException?displayProperty=nameWithType> zdarzeń z dostępem do wyjątku.</span><span class="sxs-lookup"><span data-stu-id="99519-102">This class provides the exception handler for the <xref:System.AppDomain.FirstChanceException?displayProperty=nameWithType> event with access to the exception.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="99519-103">Poniższy przykład tworzy serię domen aplikacji o nazwie `Child_0` za pośrednictwem `Child_3`, z `Worker` obiektów w każdej domenie aplikacji.</span><span class="sxs-lookup"><span data-stu-id="99519-103">The following example creates a series of application domains named `Child_0` through `Child_3`, with a `Worker` object in each application domain.</span></span> <span data-ttu-id="99519-104">Każdy `Worker` obiekt odwołuje się do `Worker` obiektu w następnej domeny aplikacji, z wyjątkiem `Worker` w ostatnim domeny aplikacji.</span><span class="sxs-lookup"><span data-stu-id="99519-104">Each `Worker` object has a reference to the `Worker` object in the next application domain, except for the `Worker` in the last application domain.</span></span> <span data-ttu-id="99519-105"><xref:System.AppDomain.FirstChanceException> Zdarzenie jest obsługiwane we wszystkich domenach aplikacji z wyjątkiem `Child_1`.</span><span class="sxs-lookup"><span data-stu-id="99519-105">The <xref:System.AppDomain.FirstChanceException> event is handled in all application domains except `Child_1`.</span></span>  
  
 <span data-ttu-id="99519-106">Podczas tworzenia domeny aplikacji domyślnej domeny aplikacji wywołuje `TestException` metody pierwszy podrzędny domeny aplikacji.</span><span class="sxs-lookup"><span data-stu-id="99519-106">When the application domains have been created, the default application domain calls the `TestException` method for the first child application domain.</span></span> <span data-ttu-id="99519-107">Każdy `Worker` obiektu wywołania `TestException` metodę dalej, aż do ostatniego `Worker` zgłasza wyjątek, który jest obsługiwany lub nieobsługiwany.</span><span class="sxs-lookup"><span data-stu-id="99519-107">Each `Worker` object calls the `TestException` method for the next, until the last `Worker` throws an exception that is either handled or unhandled.</span></span> <span data-ttu-id="99519-108">W związku z tym bieżący wątek przechodzi przez wszystkie domeny aplikacji i `TestException` zostanie dodany do stosu w każdej domenie aplikacji.</span><span class="sxs-lookup"><span data-stu-id="99519-108">Thus, the current thread passes through all the application domains, and `TestException` is added to the stack in each application domain.</span></span>  
  
 <span data-ttu-id="99519-109">Podczas ostatniego `Worker` obiektu obsługuje wyjątek, <xref:System.AppDomain.FirstChanceException> zdarzenie jest wywoływane tylko w ostatnim domeny aplikacji.</span><span class="sxs-lookup"><span data-stu-id="99519-109">When the last `Worker` object handles the exception, the <xref:System.AppDomain.FirstChanceException> event is raised only in the last application domain.</span></span> <span data-ttu-id="99519-110">Domeny aplikacji nigdy nie uzyskać możliwość obsługi wyjątku, aby zdarzenie nie jest wywoływane.</span><span class="sxs-lookup"><span data-stu-id="99519-110">The other application domains never get a chance to handle the exception, so the event is not raised.</span></span>  
  
 <span data-ttu-id="99519-111">Podczas ostatniego `Worker` obiekt nie obsługuje wyjątek, <xref:System.AppDomain.FirstChanceException> zdarzenie jest zgłaszane w każdej domenie aplikacji, która ma obsługi zdarzeń.</span><span class="sxs-lookup"><span data-stu-id="99519-111">When the last `Worker` object does not handle the exception, the <xref:System.AppDomain.FirstChanceException> event is raised in each application domain that has an event handler.</span></span> <span data-ttu-id="99519-112">Po zakończeniu każdej obsługi zdarzeń stosu w dalszym ciągu unwind dopóki wyjątek zostanie przechwycony przez domyślnej domeny aplikacji.</span><span class="sxs-lookup"><span data-stu-id="99519-112">After each event handler has finished, the stack continues to unwind until the exception is caught by the default application domain.</span></span>  
  
> [!NOTE]
>  <span data-ttu-id="99519-113">Aby zobaczyć sposób wyświetlania stosu zwiększa się w miarę zdarzenie jest wywoływane bliżej i bliżej domyślnej domeny aplikacji, należy zmienić `e.Exception.Message` do `e.Exception` w `FirstChanceHandler` procedury obsługi zdarzeń.</span><span class="sxs-lookup"><span data-stu-id="99519-113">To see how the stack display grows as the event is raised closer and closer to the default application domain, change `e.Exception.Message` to `e.Exception` in the `FirstChanceHandler` event handlers.</span></span> <span data-ttu-id="99519-114">Zwróć uwagę, że w przypadku `TestException` jest wywoływana przez granice domeny aplikacji, zostanie wyświetlone dwa razy: raz dla serwera proxy i raz dla elementu zastępczego.</span><span class="sxs-lookup"><span data-stu-id="99519-114">Notice that when `TestException` is called across application domain boundaries, it appears twice: once for the proxy and once for the stub.</span></span>  
  
 [!code-csharp[System.AppDomain.FirstChanceException#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.appdomain.firstchanceexception/cs/example.cs#1)]
 [!code-vb[System.AppDomain.FirstChanceException#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.appdomain.firstchanceexception/vb/example.vb#1)]  
  
 ]]></format>
    </remarks>
    <altmember cref="E:System.AppDomain.FirstChanceException" />
  </Docs>
  <Members>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public FirstChanceExceptionEventArgs (Exception exception);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(class System.Exception exception) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.#ctor(System.Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; FirstChanceExceptionEventArgs(Exception ^ exception);" />
      <MemberSignature Language="F#" Value="new System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs : Exception -&gt; System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" Usage="new System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs exception" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="exception" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="exception">
          <span data-ttu-id="99519-115">Wyjątek, który właśnie został zgłoszony przez kod zarządzany, i który będzie rozpatrywane przez <see cref="E:System.AppDomain.UnhandledException" /> zdarzeń.</span>
          <span class="sxs-lookup">
            <span data-stu-id="99519-115">The exception that was just thrown by managed code, and that will be examined by the <see cref="E:System.AppDomain.UnhandledException" /> event.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="99519-116">Inicjuje nowe wystąpienie klasy <see cref="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" /> z określonym wyjątkiem.</span>
          <span class="sxs-lookup">
            <span data-stu-id="99519-116">Initializes a new instance of the <see cref="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" /> class with a specified exception.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="99519-117">Ten konstruktor jest wywoływana przez środowisko uruchomieniowe języka wspólnego, nie przez kod aplikacji.</span><span class="sxs-lookup"><span data-stu-id="99519-117">This constructor is called by the common language runtime, not by application code.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="Exception">
      <MemberSignature Language="C#" Value="public Exception Exception { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance class System.Exception Exception" />
      <MemberSignature Language="DocId" Value="P:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception" />
      <MemberSignature Language="VB.NET" Value="Public ReadOnly Property Exception As Exception" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; property Exception ^ Exception { Exception ^ get(); };" />
      <MemberSignature Language="F#" Value="member this.Exception : Exception" Usage="System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute>
          <AttributeName>get: System.Runtime.ConstrainedExecution.ReliabilityContract(System.Runtime.ConstrainedExecution.Consistency.WillNotCorruptState, System.Runtime.ConstrainedExecution.Cer.Success)</AttributeName>
        </Attribute>
      </Attributes>
      <ReturnValue>
        <ReturnType>System.Exception</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
          <span data-ttu-id="99519-118">Obiekt zarządzanym wyjątku, który odpowiada wyjątek w kodzie zarządzanym.</span>
          <span class="sxs-lookup">
            <span data-stu-id="99519-118">The managed exception object that corresponds to the exception thrown in managed code.</span>
          </span>
        </summary>
        <value>
          <span data-ttu-id="99519-119">Nowo zwrócony wyjątek.</span>
          <span class="sxs-lookup">
            <span data-stu-id="99519-119">The newly thrown exception.</span>
          </span>
        </value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="99519-120">Metoda obsługująca <xref:System.AppDomain.UnhandledException?displayProperty=nameWithType> zdarzeń można zbadać wyjątek i wykonać odpowiednie rejestrowania lub innych usług powiadomień.</span><span class="sxs-lookup"><span data-stu-id="99519-120">The method that handles the <xref:System.AppDomain.UnhandledException?displayProperty=nameWithType> event can examine the exception and perform appropriate logging or other notification services.</span></span>  
  
 <span data-ttu-id="99519-121">Na przykład kodu, zobacz <xref:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs>.</span><span class="sxs-lookup"><span data-stu-id="99519-121">For example code, see <xref:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs>.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>