<Type Name="XamlSchemaException" FullName="System.Xaml.XamlSchemaException">
  <Metadata>
    <Meta Name="ms.openlocfilehash" Value="781495c63716bfa9612353c36d8ab6d63824e4dd" />
    <Meta Name="ms.sourcegitcommit" Value="d877ae76e9e11799bf919379507239e2c4072742" />
    <Meta Name="ms.translationtype" Value="MT" />
    <Meta Name="ms.contentlocale" Value="pl-PL" />
    <Meta Name="ms.lasthandoff" Value="08/09/2018" />
    <Meta Name="ms.locfileid" Value="39968084" />
  </Metadata>
  <TypeSignature Language="C#" Value="public class XamlSchemaException : System.Xaml.XamlException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable beforefieldinit XamlSchemaException extends System.Xaml.XamlException" />
  <TypeSignature Language="DocId" Value="T:System.Xaml.XamlSchemaException" />
  <TypeSignature Language="VB.NET" Value="Public Class XamlSchemaException&#xA;Inherits XamlException" />
  <TypeSignature Language="C++ CLI" Value="public ref class XamlSchemaException : System::Xaml::XamlException" />
  <TypeSignature Language="F#" Value="type XamlSchemaException = class&#xA;    inherit XamlException" />
  <AssemblyInfo>
    <AssemblyName>System.Xaml</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Xaml.XamlException</BaseTypeName>
  </Base>
  <Interfaces />
  <Docs>
    <summary>
      <span data-ttu-id="4320f-101">Wyjątek, który jest generowany, gdy system powiązań lub innego systemu reprezentujący schemat dla XAML zgłasza wyjątek, aby kontekst schematu.</span>
      <span class="sxs-lookup">
        <span data-stu-id="4320f-101">The exception that is thrown when a binding system or another schema representation system for XAML reports an exception to the schema context.</span>
      </span>
    </summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="4320f-102"><xref:System.Xaml.XamlSchemaException> Jest generowany przez kilka przypadków w klasach obsługi CLR powiązania, które zapewnia kontekst schematu dla usług programu .NET Framework XAML (<xref:System.Xaml.XamlXmlReader>, <xref:System.Xaml.XamlObjectWriter>, lub <xref:System.Xaml.XamlServices>).</span><span class="sxs-lookup"><span data-stu-id="4320f-102">The <xref:System.Xaml.XamlSchemaException> is thrown by several cases in the CLR binding support classes that provide the schema context for .NET Framework XAML Services (<xref:System.Xaml.XamlXmlReader>, <xref:System.Xaml.XamlObjectWriter>, or <xref:System.Xaml.XamlServices>).</span></span> <span data-ttu-id="4320f-103">A <xref:System.Xaml.XamlSchemaException> zwykle jest przekazywany jako wyjątek wewnętrzny, aby inne wyjątki, na przykład <xref:System.Xaml.XamlMember.IsUnknown%2A?displayProperty=nameWithType>— wartość true, właściwość <xref:System.Xaml.XamlObjectWriterException>, więc powinno być rzadkie catch <xref:System.Xaml.XamlSchemaException> bezpośrednio, chyba że w przypadku takich jak wdrażania składnika Specjalizowany obiekt składnika zapisywania.</span><span class="sxs-lookup"><span data-stu-id="4320f-103">A <xref:System.Xaml.XamlSchemaException> is typically passed as the inner exception for other exceptions, such as the <xref:System.Xaml.XamlMember.IsUnknown%2A?displayProperty=nameWithType>-true property for a <xref:System.Xaml.XamlObjectWriterException>, so it should be uncommon to catch a <xref:System.Xaml.XamlSchemaException> directly unless you are implementing a component such as a specialized object writer.</span></span>  
  
 ]]></format>
    </remarks>
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>System.Xaml</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary>
          <span data-ttu-id="4320f-104">Inicjuje nowe wystąpienie klasy <see cref="T:System.Xaml.XamlSchemaException" /> klasy.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4320f-104">Initializes a new instance of the <see cref="T:System.Xaml.XamlSchemaException" /> class.</span>
          </span>
        </summary>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public XamlSchemaException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Xaml.XamlSchemaException.#ctor" />
      <MemberSignature Language="VB.NET" Value="Public Sub New ()" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; XamlSchemaException();" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Xaml</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0">
          <AttributeName>System.Runtime.TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")</AttributeName>
        </Attribute>
      </Attributes>
      <Parameters />
      <Docs>
        <summary>
          <span data-ttu-id="4320f-105">Inicjuje nowe wystąpienie klasy <see cref="T:System.Xaml.XamlSchemaException" /> klasie z atrybutem dostarczane przez system komunikatu, który opisuje błąd.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4320f-105">Initializes a new instance of the <see cref="T:System.Xaml.XamlSchemaException" /> class with a system-supplied message that describes the error.</span>
          </span>
        </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public XamlSchemaException (string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Xaml.XamlSchemaException.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; XamlSchemaException(System::String ^ message);" />
      <MemberSignature Language="F#" Value="new System.Xaml.XamlSchemaException : string -&gt; System.Xaml.XamlSchemaException" Usage="new System.Xaml.XamlSchemaException message" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Xaml</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="4320f-106">Komunikat, który opisuje wyjątek.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4320f-106">The message that describes the exception.</span>
          </span>
          <span data-ttu-id="4320f-107">Obiekt wywołujący tego konstruktora jest wymagany w celu zagwarantowania, że ten ciąg został zlokalizowany w bieżącej kulturze systemu.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4320f-107">The caller of this constructor is required to ensure that this string has been localized for the current system culture.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="4320f-108">Inicjuje nowe wystąpienie klasy <see cref="T:System.Xaml.XamlSchemaException" /> klasy przy użyciu określonego komunikatu, który opisuje błąd.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4320f-108">Initializes a new instance of the <see cref="T:System.Xaml.XamlSchemaException" /> class with a specified message that describes the error.</span>
          </span>
        </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="protected XamlSchemaException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);" />
      <MemberSignature Language="ILAsm" Value=".method familyhidebysig specialname rtspecialname instance void .ctor(class System.Runtime.Serialization.SerializationInfo info, valuetype System.Runtime.Serialization.StreamingContext context) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Xaml.XamlSchemaException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />
      <MemberSignature Language="VB.NET" Value="Protected Sub New (info As SerializationInfo, context As StreamingContext)" />
      <MemberSignature Language="C++ CLI" Value="protected:&#xA; XamlSchemaException(System::Runtime::Serialization::SerializationInfo ^ info, System::Runtime::Serialization::StreamingContext context);" />
      <MemberSignature Language="F#" Value="new System.Xaml.XamlSchemaException : System.Runtime.Serialization.SerializationInfo * System.Runtime.Serialization.StreamingContext -&gt; System.Xaml.XamlSchemaException" Usage="new System.Xaml.XamlSchemaException (info, context)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Xaml</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0">
          <AttributeName>System.Runtime.TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")</AttributeName>
        </Attribute>
      </Attributes>
      <Parameters>
        <Parameter Name="info" Type="System.Runtime.Serialization.SerializationInfo" />
        <Parameter Name="context" Type="System.Runtime.Serialization.StreamingContext" />
      </Parameters>
      <Docs>
        <param name="info">
          <span data-ttu-id="4320f-109">Obiekt zawierający dane serializowanego obiektu.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4320f-109">The object that holds the serialized object data.</span>
          </span>
        </param>
        <param name="context">
          <span data-ttu-id="4320f-110">Informacje kontekstowe o źródłowego lub miejscu docelowym.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4320f-110">The contextual information about the source or destination.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="4320f-111">Inicjuje nowe wystąpienie klasy <see cref="T:System.Xaml.XamlSchemaException" /> klasy z serializowanych danych.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4320f-111">Initializes a new instance of the <see cref="T:System.Xaml.XamlSchemaException" /> class with serialized data.</span>
          </span>
        </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public XamlSchemaException (string message, Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Xaml.XamlSchemaException.#ctor(System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; XamlSchemaException(System::String ^ message, Exception ^ innerException);" />
      <MemberSignature Language="F#" Value="new System.Xaml.XamlSchemaException : string * Exception -&gt; System.Xaml.XamlSchemaException" Usage="new System.Xaml.XamlSchemaException (message, innerException)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Xaml</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0">
          <AttributeName>System.Runtime.TargetedPatchingOptOut("Performance critical to inline this type of method across NGen image boundaries")</AttributeName>
        </Attribute>
      </Attributes>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="4320f-112">Komunikat, który opisuje wyjątek.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4320f-112">The message that describes the exception.</span>
          </span>
          <span data-ttu-id="4320f-113">Obiekt wywołujący tego konstruktora jest wymagany w celu zagwarantowania, że ten ciąg został zlokalizowany w bieżącej kulturze systemu.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4320f-113">The caller of this constructor is required to ensure that this string has been localized for the current system culture.</span>
          </span>
        </param>
        <param name="innerException">
          <span data-ttu-id="4320f-114">Wyjątek, który jest przyczyną bieżącego wyjątku.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4320f-114">The exception that is the cause of the current exception.</span>
          </span>
          <span data-ttu-id="4320f-115">Jeśli <c>innerException</c> parametr nie jest <see langword="null" />, bieżący wyjątek jest zgłaszany w <see langword="catch" /> blok, który obsługuje wyjątek wewnętrzny.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4320f-115">If the <c>innerException</c> parameter is not <see langword="null" />, the current exception is raised in a <see langword="catch" /> block that handles the inner exception.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="4320f-116">Inicjuje nowe wystąpienie klasy <see cref="T:System.Xaml.XamlSchemaException" /> klasy przy użyciu określonego komunikatu o błędzie i odwołania do wewnętrznego wyjątku, który jest przyczyną tego wyjątku.</span>
          <span class="sxs-lookup">
            <span data-stu-id="4320f-116">Initializes a new instance of the <see cref="T:System.Xaml.XamlSchemaException" /> class with a specified error message and a reference to the inner exception that is the cause of this exception.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="4320f-117">Wyjątek generowany jako bezpośredni wynik poprzedniego wyjątku powinien zawierać odwołanie do poprzedniego wyjątku we <xref:System.Exception.InnerException%2A> właściwości.</span><span class="sxs-lookup"><span data-stu-id="4320f-117">An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property.</span></span> <span data-ttu-id="4320f-118"><xref:System.Exception.InnerException%2A> Właściwość zwraca taką samą wartość, która jest przekazywana do konstruktora, lub `null` Jeśli <xref:System.Exception.InnerException%2A> nie dostarcza wartości wewnętrznego wyjątku do konstruktora.</span><span class="sxs-lookup"><span data-stu-id="4320f-118">The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>