<Type Name="AddressAlreadyInUseException" FullName="System.ServiceModel.AddressAlreadyInUseException">
  <Metadata>
    <Meta Name="ms.openlocfilehash" Value="d1dd02a2bc0ff1d728d9631bb8be0fcf59966b3d" />
    <Meta Name="ms.sourcegitcommit" Value="3907f9a5780957d9c85af2e54c0a5bc2a5bf19ab" />
    <Meta Name="ms.translationtype" Value="MT" />
    <Meta Name="ms.contentlocale" Value="pl-PL" />
    <Meta Name="ms.lasthandoff" Value="06/14/2018" />
    <Meta Name="ms.locfileid" Value="34312930" />
  </Metadata>
  <TypeSignature Language="C#" Value="public class AddressAlreadyInUseException : System.ServiceModel.CommunicationException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable beforefieldinit AddressAlreadyInUseException extends System.ServiceModel.CommunicationException" />
  <TypeSignature Language="DocId" Value="T:System.ServiceModel.AddressAlreadyInUseException" />
  <TypeSignature Language="VB.NET" Value="Public Class AddressAlreadyInUseException&#xA;Inherits CommunicationException" />
  <TypeSignature Language="C++ CLI" Value="public ref class AddressAlreadyInUseException : System::ServiceModel::CommunicationException" />
  <AssemblyInfo>
    <AssemblyName>System.ServiceModel</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.ServiceModel.CommunicationException</BaseTypeName>
  </Base>
  <Interfaces />
  <Docs>
    <summary>
      <span data-ttu-id="bd593-101">Wyjątek zgłaszany, gdy adres jest niedostępny, ponieważ jest już używana.</span>
      <span class="sxs-lookup">
        <span data-stu-id="bd593-101">The exception that is thrown when an address is unavailable because it is already in use.</span>
      </span>
    </summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="bd593-102">Ten wyjątek pochodzi z <xref:System.ServiceModel.CommunicationException> reprezentujący klasę nieodwracalny błędów, które może zostać zgłoszony podczas komunikacji między punktami końcowymi i niezawodne klienta usługi Windows Communication Foundation (WCF) i usługi aplikacje powinny obsługiwać.</span><span class="sxs-lookup"><span data-stu-id="bd593-102">This exception derives from <xref:System.ServiceModel.CommunicationException> that represents a class of recoverable errors that may be thrown during communication between endpoints and that robust Windows Communication Foundation (WCF) client and service applications are expected to handle.</span></span> <span data-ttu-id="bd593-103">Aby zapobiec obsługi dla <xref:System.ServiceModel.CommunicationException> z konkretnym więcej Przechwytywanie <xref:System.ServiceModel.AddressAlreadyInUseException>, przechwycić tego wyjątku przed Obsługa <xref:System.ServiceModel.CommunicationException>.</span><span class="sxs-lookup"><span data-stu-id="bd593-103">To prevent a handler for <xref:System.ServiceModel.CommunicationException> from catching the more specific <xref:System.ServiceModel.AddressAlreadyInUseException>, catch this exception prior to handling <xref:System.ServiceModel.CommunicationException>.</span></span>  
  
 ]]></format>
    </remarks>
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>System.ServiceModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary>
          <span data-ttu-id="bd593-104">Inicjuje nowe wystąpienie klasy <see cref="T:System.ServiceModel.AddressAlreadyInUseException" /> klasy.</span>
          <span class="sxs-lookup">
            <span data-stu-id="bd593-104">Initializes a new instance of the <see cref="T:System.ServiceModel.AddressAlreadyInUseException" /> class.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="bd593-105">Jeśli chcesz przekazać komunikat o błędzie dla użytkownika, użyj <xref:System.ServiceModel.AddressAlreadyInUseException.%23ctor%28System.String%29> konstruktora.</span><span class="sxs-lookup"><span data-stu-id="bd593-105">If you want to pass an error message to the user, use the <xref:System.ServiceModel.AddressAlreadyInUseException.%23ctor%28System.String%29> constructor.</span></span>  
  
 <span data-ttu-id="bd593-106">Jeśli chcesz przekazać komunikat o błędzie i odwołania wyjątek wewnętrzny, który jest przyczyną wyjątku, aby użytkownik, użyj <xref:System.ServiceModel.AddressAlreadyInUseException.%23ctor%28System.String%2CSystem.Exception%29> konstruktora.</span><span class="sxs-lookup"><span data-stu-id="bd593-106">If you want to pass an error message and a reference to the inner exception that is the cause of the exception to the user, use the <xref:System.ServiceModel.AddressAlreadyInUseException.%23ctor%28System.String%2CSystem.Exception%29> constructor.</span></span>  
  
 <span data-ttu-id="bd593-107">Jeśli chcesz przekazać informacje serializacji i kontekst przesyłania strumieniowego, użyj <xref:System.ServiceModel.AddressAlreadyInUseException.%23ctor%28System.Runtime.Serialization.SerializationInfo%2CSystem.Runtime.Serialization.StreamingContext%29> konstruktora.</span><span class="sxs-lookup"><span data-stu-id="bd593-107">If you want to pass serialization information and streaming context, use the <xref:System.ServiceModel.AddressAlreadyInUseException.%23ctor%28System.Runtime.Serialization.SerializationInfo%2CSystem.Runtime.Serialization.StreamingContext%29> constructor.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AddressAlreadyInUseException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.ServiceModel.AddressAlreadyInUseException.#ctor" />
      <MemberSignature Language="VB.NET" Value="Public Sub New ()" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; AddressAlreadyInUseException();" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.ServiceModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary>
          <span data-ttu-id="bd593-108">Inicjuje nowe wystąpienie klasy <see cref="T:System.ServiceModel.AddressAlreadyInUseException" /> klasy.</span>
          <span class="sxs-lookup">
            <span data-stu-id="bd593-108">Initializes a new instance of the <see cref="T:System.ServiceModel.AddressAlreadyInUseException" /> class.</span>
          </span>
        </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AddressAlreadyInUseException (string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.ServiceModel.AddressAlreadyInUseException.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; AddressAlreadyInUseException(System::String ^ message);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.ServiceModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="bd593-109">Komunikat o błędzie wyjaśniający przyczynę wyjątku.</span>
          <span class="sxs-lookup">
            <span data-stu-id="bd593-109">The error message that explains the reason for the exception.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="bd593-110">Inicjuje nowe wystąpienie klasy <see cref="T:System.ServiceModel.AddressAlreadyInUseException" /> klasy z powodu określonego błędu.</span>
          <span class="sxs-lookup">
            <span data-stu-id="bd593-110">Initializes a new instance of the <see cref="T:System.ServiceModel.AddressAlreadyInUseException" /> class with a specified error message.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="bd593-111">Użyj tego konstruktora, jeśli chcesz przekazać komunikat o błędzie dla użytkownika.</span><span class="sxs-lookup"><span data-stu-id="bd593-111">Use this constructor when you want to pass an error message to the user.</span></span> <span data-ttu-id="bd593-112">Zawartość parametru wiadomości powinna być zrozumiała dla danego użytkownika.</span><span class="sxs-lookup"><span data-stu-id="bd593-112">The content of the message parameter should be understandable to the intended user.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="protected AddressAlreadyInUseException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);" />
      <MemberSignature Language="ILAsm" Value=".method familyhidebysig specialname rtspecialname instance void .ctor(class System.Runtime.Serialization.SerializationInfo info, valuetype System.Runtime.Serialization.StreamingContext context) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.ServiceModel.AddressAlreadyInUseException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />
      <MemberSignature Language="VB.NET" Value="Protected Sub New (info As SerializationInfo, context As StreamingContext)" />
      <MemberSignature Language="C++ CLI" Value="protected:&#xA; AddressAlreadyInUseException(System::Runtime::Serialization::SerializationInfo ^ info, System::Runtime::Serialization::StreamingContext context);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.ServiceModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="info" Type="System.Runtime.Serialization.SerializationInfo" />
        <Parameter Name="context" Type="System.Runtime.Serialization.StreamingContext" />
      </Parameters>
      <Docs>
        <param name="info">
          <span data-ttu-id="bd593-113">
            <see cref="T:System.Runtime.Serialization.SerializationInfo" /> Zawierający wszystkie dane wymagane do serializacji wyjątek.</span>
          <span class="sxs-lookup">
            <span data-stu-id="bd593-113">The <see cref="T:System.Runtime.Serialization.SerializationInfo" /> that contains all the data required to serialize the exception.</span>
          </span>
        </param>
        <param name="context">
          <span data-ttu-id="bd593-114">
            <see cref="T:System.Runtime.Serialization.StreamingContext" /> , Który określa źródłowy i docelowy strumienia.</span>
          <span class="sxs-lookup">
            <span data-stu-id="bd593-114">The <see cref="T:System.Runtime.Serialization.StreamingContext" /> that specifies the source and destination of the stream.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="bd593-115">Inicjuje nowe wystąpienie klasy <see cref="T:System.ServiceModel.AddressAlreadyInUseException" /> klasy informacje serializacji i określony kontekst przesyłania strumieniowego.</span>
          <span class="sxs-lookup">
            <span data-stu-id="bd593-115">Initializes a new instance of the <see cref="T:System.ServiceModel.AddressAlreadyInUseException" /> class with serialization information and streaming context specified.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="bd593-116">Ten konstruktor jest wywoływana podczas deserializacji, aby odtworzyć obiekt wyjątku przesyłane przez strumień.</span><span class="sxs-lookup"><span data-stu-id="bd593-116">This constructor is called during deserialization to reconstruct the exception object transmitted over a stream.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AddressAlreadyInUseException (string message, Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.ServiceModel.AddressAlreadyInUseException.#ctor(System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; AddressAlreadyInUseException(System::String ^ message, Exception ^ innerException);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.ServiceModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="bd593-117">Komunikat o błędzie wyjaśniający przyczynę wyjątku.</span>
          <span class="sxs-lookup">
            <span data-stu-id="bd593-117">The error message that explains the reason for the exception.</span>
          </span>
        </param>
        <param name="innerException">
          <span data-ttu-id="bd593-118">
            <see cref="T:System.Exception" /> , Która spowodowała bieżący wyjątek zostanie wygenerowany.</span>
          <span class="sxs-lookup">
            <span data-stu-id="bd593-118">The <see cref="T:System.Exception" /> that caused the current exception to be thrown.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="bd593-119">Inicjuje nowe wystąpienie klasy <see cref="T:System.ServiceModel.AddressAlreadyInUseException" /> z określonego komunikatu o błędzie i odwołania do wyjątek wewnętrzny będący przyczyną tego wyjątku.</span>
          <span class="sxs-lookup">
            <span data-stu-id="bd593-119">Initializes a new instance of the <see cref="T:System.ServiceModel.AddressAlreadyInUseException" /> class with a specified error message and a reference to the inner exception that is the cause of the exception.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="bd593-120">Użyj tego konstruktora, jeśli chcesz przekazać komunikat o błędzie i informacje o wewnętrzny wyjątek do użytkownika.</span><span class="sxs-lookup"><span data-stu-id="bd593-120">Use this constructor when you want to pass an error message and information about an inner exception up to the user.</span></span> <span data-ttu-id="bd593-121">Zawartość parametru wiadomości powinna być zrozumiała dla uprawnionych użytkowników.</span><span class="sxs-lookup"><span data-stu-id="bd593-121">The content of the message parameter should be understandable to the intended users.</span></span>  
  
 <span data-ttu-id="bd593-122">Wyjątek zgłaszany bezpośrednio w wyniku poprzedniego wyjątku może zawierać odwołania do poprzedniego wyjątku we <xref:System.Exception.InnerException%2A> właściwości.</span><span class="sxs-lookup"><span data-stu-id="bd593-122">An exception that is thrown as a direct result of a previous exception can include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property.</span></span> <span data-ttu-id="bd593-123"><xref:System.Exception.InnerException%2A> Właściwość zwraca tę samą wartość, która została przekazana do konstruktora, lub `null` odwołania (`Nothing` w języku Visual Basic) Jeśli <xref:System.Exception.InnerException%2A> właściwości nie dostarcza do konstruktora wartości wyjątku wewnętrznego.</span><span class="sxs-lookup"><span data-stu-id="bd593-123">The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or a `null` reference (`Nothing` in Visual Basic) if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>